version: "2"

services:
  bitlbee:
    # build: .
    image: thomasf/bitlbee:v1.0.0
    restart: on-failure
    volumes:
      - /srv/bitlbee/var:/var/lib/bitlbee
    ports:
      - "127.0.0.1:30001:6667"
